version: '3.9'

networks:
  web_network:
    external: true

services:
  # Bot
  travian-bot:
    build: .
    image: travian-bot:latest
    container_name: travian-bot
    restart: unless-stopped
    volumes:
      - ./bot:/usr/src/travian-bot/bot
      - .env:/usr/src/travian-bot/.env
      - config.yml:/usr/src/travian-bot/config.yml
      - .data.yml:/usr/src/travian-bot/.data.yml
      - ./chrome-settings:/usr/src/travian-bot/.chrome-settings
    networks:
      - web_network
    ports:
      - ${TELEGRAM_WEBHOOK_PORT}:${TELEGRAM_WEBHOOK_PORT}
